import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react"; // Use the `/react` extension here

export const stockApi = createApi({
  reducerPath: "stockApi",
  baseQuery: fetchBaseQuery({ baseUrl: "http://localhost:8000/api/" }),
  tagTypes: ["Stock"],
  endpoints: (builder) => ({
    getStockItems: builder.query({
      query: () => "stock/stock_api_view/",
      providesTags: ["Stock"],
    }),
  }),
});

// Export the hook generated by RTK Query
export const { useGetStockItemsQuery } = stockApi;
